#ifndef  _affichage_h_
#define _affichage_h_

//$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$ Declarations des fonctions dans le .cpp $$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$
void affichageHeureNextion();
void affichePageBrassage();
void affichePageConfig();
void affichePageHorloge();
void affichePageInfo();
void affichePageMenu();
void affichePageTel();
void affichePageWifi();
void boutonBlanc(void *ptr);
void boutonBleu(void *ptr);
void boutonBrassage1(void *ptr);
void boutonBrassage2(void *ptr);
void boutonBrassage3(void *ptr);
void boutonNourrissageManuel(void *ptr);
void boutonOnOffAlim1(void *ptr);
void boutonOnOffAlim2(void *ptr);
void boutonOnOffRemonte(void *ptr);
void boutonoscillo1();
void boutonoscillo1max(void *ptr);
void boutonoscillo1min(void *ptr);
void boutonoscillo2();
void boutonoscillo2max(void *ptr);
void boutonoscillo2min(void *ptr);
void boutonoscillo3();
void boutonoscillo3max(void *ptr);
void boutonoscillo3min(void *ptr);
void boutonTempeteAleatoire(void *ptr);
void boutonTempeteManuel(void *ptr);
void effaceBufferTexte();
void effaceminuteEnTexteIn();
void enregistrerBrassage(void *ptr);
void enregistrerConfig(void *ptr);
void enregistrerHorloge(void *ptr);
void enregistrerTel(void *ptr);
void enregistrerWifi(void *ptr);
void horraireEnSeconde(uint32_t h, uint16_t d, uint16_t m);
void afficherNourrissageEnCoursOff();
void numEnChar (uint8_t numeriqueEnChar);
void rafraichirBrassage1Nextion();
void rafraichirBrassage2Nextion();
void rafraichirBrassage3Nextion();
void rafraichirEclairageBlancNextion();
void rafraichirEclairageBleuNextion();
void rafraichirHeureSiSurMenu();
void rafraichirPhBacNextion();
void rafraichirPhRacNextion();
void rafraichirTemperatureBacNextion();
void rafraichirTemperatureRampeNextion();
void rafraichirIconeBatterie();
void rafraichirSignalWifi();
void rafraichirSignalGSM();
void reinitialisationDeLaffichage();
void statutBlanc();
void statutBleu();
void statutBrassage1();
void statutBrassage2();
void statutBrassage3();
void statutOnOffAlim1();
void statutOnOffAlim2();
void statutNourrissageEnCours();
void statutOnOffDelay();
void statutTempete();
void statutTempeteAleatoire();
void tempeteNextion();
void afficherNourrissageEnCours();
void versBrassage(void *ptr);
void versConfig(void *ptr);
void versHorloge(void *ptr);
void versInfo(void *ptr);
void versMenu(void *ptr);
void versTel(void *ptr);
void versWifi(void *ptr);
void versStandby(void *ptr);
void afficherAlerteOsmolation();
void afficherAlerteOsmolationOff();
void afficherAlerteOsmolationOffReserveVide();
void afficherAlertepPhBacBas();
void afficherAlertepPhBacHaut();
void afficherAlertepPhBacOff();
void etalonnage(void *ptr);
void lectureBoutons();
void etalonnageOFF();
void texteProgmemAuNextion(NexText, const char texteEnProgmem[] PROGMEM, const uint16_t couleurTexte);
void texteAuNextion(NexText champTexte, char*texte, const uint16_t couleurTexte);

#endif
